#!/usr/bin/env bash
# Loops 1 to 10, prints bad luck on 4th, good luck on 8th, Best School otherwise
i=0
while [ $i -lt 10 ]
do
i=$((i+1))
if [ $i -eq 4 ]
then
echo "bad luck"
elif [ $i -eq 8 ]
then
echo "good luck"
else
echo "Best School"
fi
done
